services:
  app:
      build: .
      container_name: fastapi_app
      env_file:
        - .env
      depends_on:
        - db
      ports:
        - "8000:8000"
  db:
    image: postgres:17.6-alpine
    container_name: postgres_db
    env_file:
      - .env
    ports:
      - "5432:5432"
